### ISSUE TITLE
Erro quando não passa json via método post

### ISSUE THREAD

**Issue by marcelorafaelfeil** [jspare-projects/vertx-jspare#4]
Quando envio uma requisição para uma rota POST que espera receber um json como parâmetro mas passo o parâmetro nulo, é retornado o seguinte erro:

_io.vertx.core.json.DecodeException: Failed to decode: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at io.vertx.core.json.Json.decodeValue(Json.java:123)
	at org.jspare.vertx.web.handler.DefaultHandler.resolveParameter(DefaultHandler.java:227)
	at org.jspare.vertx.web.handler.DefaultHandler.collectParameters(DefaultHandler.java:131)
	at org.jspare.vertx.web.handler.DefaultHandler.handle(DefaultHandler.java:90)
	at org.jspare.vertx.web.handler.DefaultHandler.handle(DefaultHandler.java:42)_

O problema é que não consigo tratar esse erro.

**Comment by jspare-projects** [comment]
Hello Marcelo, 

Thank's for your feedback.

This issue are fixed by commit: 3ef1ca9ea94672438255adfab9cb77efcd1bc8ff

And was released in version 3.1.1 please update your dependency and enjoy.

Regards
